{% set version = "0.0.1" %}

package:
  name: intake-esgf
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python

  host:
    - python

  run:
    - python
    - requests
    - intake
    - intake-xarray
    - fsspec

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
    - ipywidgets

  source_files:
    - intake_esgf/tests/
    - conftest.py

  commands:
    - pytest -vvv intake_esgf/tests/

  imports:
    - intake_esgf
    - intake_esgf.core
    - intake_esgf.tools

about:
  home: https://github.com/ESGF/intake-esgf
