name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -L -o conda.sh
          
          bash ${PWD}/conda.sh -b -p ${PWD}/conda
      - name: Build Conda package
        run: |
          export PATH=${PWD}/conda/bin:${PATH}

          make build-env

          make build
