name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          pwd

          pushd ${HOME}

          curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o conda.sh

          bash conda.sh -b -p ${HOME}/conda

          popd

          export PATH=${HOME}/conda/bin:${PATH}

          make build-env

          make rerender
      - name: Build
        if: ${{ contains(github.ref, 'master') }}
        run: |
          export PATH=${HOME}/conda/bin:${PATH}

          make build CONDA_EXTRA=--no-anaconda-upload
      - name: Build and Upload
        if: ${{ startsWith(github.ref, 'v') }}
        env:
          CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
        run: |
          export PATH=${PATH}/conda/bin:${PATH}

          make build CONDA_EXTRA="--skip-existing --token ${CONDA_TOKEN}"
