name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          [[ ! -e ${PWD}/conda.sh ]] && curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -L -o conda.sh
          
          bash ./conda.sh -b -p ${PWD}/conda
          
          export PATH=${PWD}/conda/bin:${PATH}
          
          conda init bash
      - name: Build Conda package
        run: |
          make build-env

          make build
