name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        run: |
          pushd ${HOME}

          curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o conda.sh

          bash conda.sh -b -p ${HOME}/conda
      - name: Setup build environment
        run: make build-env
      - name: Build & Test
        run: make build 
