# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          [[ ! -e ${PWD}/conda.sh ]] && curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -L -o conda.sh
          
          bash ./conda.sh -b -p ${PWD}/conda
          
          export PATH=${PWD}/conda/bin:${PATH}
          
          conda init bash
          
          conda install -c conda-forge conda-build anaconda-client -y
          
          make build
          
          
          
