name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        run: |
          pushd ${HOME}

          curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o conda.sh

          bash conda.sh -b -p ${HOME}/conda
      - name: Setup build environment
        run: make build-env
      - name: Build & Test
        env:
          CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
        run: make build CONDA_TOKEN=${CONDA_TOKEN}
